
stages:
  - deploy

before_script:
    - pwd
    - ls
    - echo $CI_COMMIT_SHORT_SHA
    - echo $CI_COMMIT_TAG
    - echo $CI_COMMIT_BRANCH
    - echo $CI_PROJECT_DIR

# 全局緩存設置，所有分支共用相同的 NuGet 緩存
cache:
  key: "global-nuget-cache"  # 設定固定的快取鍵，讓所有分支共用相同的緩存
  paths:
    - .nuget/packages/        # 緩存 NuGet 套件
.k8s-dev-job:
  image: gcr.io/kaniko-project/executor:debug
  tags:
    - w1-kaniko
  variables:
    CONTAINER_REGISTRY: "us-docker.pkg.dev/wallet-dev-341406/gcr.io"
    APP_NAME: ""
    DOCKERFILE_PATH: ""
    CACHE_DIR: "/cache"  # 設定 Kaniko 緩存目錄
  artifacts:
    untracked: true
    expire_in: 10min
  script:
    - export GOOGLE_APPLICATION_CREDENTIALS=/kaniko/kaniko-secret.json
    - echo $GOOGLE_APPLICATION_CREDENTIALS_BASE64 | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/${DOCKERFILE_PATH}"
      --destination "${CONTAINER_REGISTRY}/${APP_NAME}:${CI_COMMIT_TAG}"
      --cache=true
      --cache-dir="${CACHE_DIR}"  # 使用 Kaniko 緩存

build_dev:
  extends: .k8s-dev-job
  stage: deploy
  variables:
    APP_NAME: "h1_thirdparty_wallet"
    DOCKERFILE_PATH: "Dockerfile"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^DEV/'

build_prd:
  extends: .k8s-dev-job
  stage: deploy
  variables:
    APP_NAME: "h1_thirdparty_wallet"
    DOCKERFILE_PATH: "Dockerfile"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^ver/'

